/**
 * Subledger service for the Dynamic Product System.
 * خدمة الدفتر الفرعي لنظام المنتجات الديناميكي
 *
 * Provides read-only operations for subledger entries (IFRS 9 compliant).
 * Subledger entries are generated by financial events (payments,
 * disbursements, penalties, early settlements, write-offs).
 * Endpoints: /api/v1/subledger
 */

import { apiClient } from '@/lib/api-client';
import type {
  PaginatedResponse,
  SubledgerEntry,
} from '@/types';

/**
 * Subledger service with all subledger query operations.
 * خدمة الدفتر الفرعي مع جميع عمليات الاستعلام
 */
export const subledgerService = {
  /**
   * List subledger entries with optional filters and pagination.
   * عرض قيود الدفتر الفرعي مع تصفية وتصفح اختياريين
   */
  listEntries(params?: {
    contract_id?: number;
    event_type?: string;
    from?: string;
    to?: string;
    dr_account?: string;
    cr_account?: string;
    page?: number;
    size?: number;
  }): Promise<PaginatedResponse<SubledgerEntry>> {
    return apiClient.get<PaginatedResponse<SubledgerEntry>>('subledger/entries', { params });
  },
};
